with(obj_planetary){
ini_open(working_directory+"save.ini");
//ini_open("save.ini");
//ds_grid_write(planetary, ini_read_string("planetary", "grid", 0));
ini_write_string("planetary", "grid", ds_grid_write(planetary));
//ds_grid_read(questgrid, ini_read_string("quest", "grid", ""));
ini_close();

ini_open(working_directory+"save2.ini");
//ini_open("save2.ini");
ini_write_real("game","GameSaves1",optiportabletaille);
ini_write_real("game","GameSaves2",moderatio);
ini_write_real("game","GameSaves3",savedate);
ini_write_real("game","GameSaves4",global.idfixe);
ini_write_string("game","GameSaves5",global.name);
ini_write_real("game","GameSaves6",global.idguild);
ini_write_string("game","GameSaves7",global.idguildname);
ini_write_real("game","GameSaves8",global.idguildinvit);
ini_write_string("game","GameSaves9",global.idguildinvitname);
ini_write_real("game","GameSaves10",global.grade);
ini_write_real("game","rcolor",rcolor);
ini_write_real("game","gcolor",gcolor);
ini_write_real("game","bcolor",bcolor);
ini_write_real("game","rcolor2",rcolor2);
ini_write_real("game","gcolor2",gcolor2);
ini_write_real("game","bcolor2",bcolor2);
ini_write_real("game","dlcpris1",dlcpris1);
ini_write_real("game","tech1",techArray[1]);
ini_write_real("game","tech2",techArray[2]);
ini_write_real("game","tech3",techArray[3]);
ini_write_real("game","tech4",techArray[4]);
ini_write_real("game","tech5",techArray[5]);
ini_write_real("game","tech6",techArray[6]);
ini_write_real("game","tech7",techArray[7]);
ini_write_real("game","tech8",techArray[8]);
ini_write_real("game","tech9",techArray[9]);
ini_write_real("game","tech10",techArray[10]);
ini_write_real("game","tech11",techArray[11]);
ini_write_real("game","tech12",techArray[12]);
ini_write_real("game","tech13",techArray[13]);
ini_write_real("game","tech14",techArray[14]);
ini_write_real("game","tech15",techArray[15]);
ini_write_real("game","tech16",techArray[16]);
ini_write_real("game","tech17",techArray[17]);
ini_write_real("game","tech18",techArray[18]);
ini_write_real("game","tech19",techArray[19]);
ini_write_real("game","tech20",techArray[20]);
ini_write_real("game","tech21",techArray[21]);
ini_write_real("game","tech22",techArray[22]);
ini_write_real("game","tech23",techArray[23]);
ini_write_real("game","tech24",techArray[24]);
ini_write_real("game","tech25",techArray[25]);
ini_write_real("game","tech26",techArray[26]);
ini_write_real("game","tech27",techArray[27]);
ini_write_real("game","tech28",techArray[28]);
ini_write_real("game","tech29",techArray[29]);
ini_write_real("game","tech30",techArray[30]);

ini_write_real("game","topm1",toPMssc1)
ini_write_real("game","topm2",toPMssc2)
ini_write_real("game","topm3",toPMssc3)
ini_write_real("game","topm4",toPMssc4)
ini_write_real("game","topm5",toPMssc5)
ini_write_real("game","topm6",toPMssc6)
ini_write_real("game","topm7",toPMssc7)
ini_write_real("game","topm8",toPMrttal)
ini_write_real("game","topm9",toPMr1)
ini_write_real("game","topm10",toPMr2)
ini_write_real("game","topm11",toPMr3)
ini_write_real("game","topm12",toPMr4)
ini_write_real("game","topm13",toPMr5)
ini_write_real("game","topm14",toPMr6)
ini_write_real("game","topm15",toPMr7)
ini_write_real("game","topm16",toPMr8)
ini_write_real("game","topm17",toPMr9)
ini_write_real("game","topm18",toPMtime)

ini_close();
}
